### ISSUE TITLE
AccessToken is null

### ISSUE THREAD

**Issue by GabrielMMI** [jasonjoh/java-tutorial#6]
Hello, I would like some help, I downloaded the git project and made the settings of Read Me, but when I run the program, the "acessToken" token is null, so the Authorization is null as shown in the code below.

```
 --> POST https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/oauth2/v2.0/token http/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 230

client_id=0b1ecc07-730f-46e8-a496-fd9c3c7f287e&client_secret=wc%3D9r%40rcaB7-fx.0jKSEufosz4EB--e5&grant_type=authorization_code&code=Mb72647ff-e0dc-0d6c-86ab-1050985d4d80&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fauthorize.html
--> END POST (230-byte body)
--> GET https://graph.microsoft.com/v1.0/me http/1.1
User-Agent: java-tutorial
client-request-id: 10165330-8012-4d79-a93b-c488390775b3
return-client-request-id: true
Authorization: Bearer null
--> END GET
[WARNING] 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:980)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.util.Date.getMillisOf(Date.java:958)
	at java.util.Date.after(Date.java:931)
	at com.outlook.dev.auth.AuthHelper.ensureTokens(AuthHelper.java:141)
	at com.outlook.dev.controller.MailController.mail(MailController.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:817)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:731)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
	... 28 more
```

**Comment by GabrielMMI** [comment]
@jasonjoh

**Comment by jasonjoh** [comment]
It sounds like your authentication is not succeeding. A network trace might shed some light here.

**Comment by GabrielMMI** [comment]
Index page:
![p1](https://user-images.githubusercontent.com/26382676/70344379-5ca87300-1838-11ea-9bb1-8f0416e9b2f7.PNG)




Mail page:
![p2](https://user-images.githubusercontent.com/26382676/70344381-5e723680-1838-11ea-8cb1-2943b1b16eda.PNG)

**Comment by jasonjoh** [comment]
Sorry, I meant a trace showing the traffic to login.microsoftonline.com.

**Comment by jasonjoh** [comment]
Closing this issue as I'm archiving this sample. We've retired the tutorial that this is based on and we're redirecting to the Microsoft Graph tutorial at https://docs.microsoft.com/graph/tutorials/java. The corresponding GitHub repo is https://github.com/microsoftgraph/msgraph-training-java.
